version: '3.4'
services:
  web:
    network_mode: host
    build:
      context: web
      dockerfile: Dockerfile
    image: mqfn/mqfn:1.0
    volumes:
      - './:/app'
    environment:
      CONTAINER_SERVER_PORT: 15333
      OUTER_PORT: 15333
    ports:
      - 15333:15333
